TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.18
  min_vel_x: 0.08

  max_vel_theta:  1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 1.0

  acc_lim_x: 1.0
  acc_lim_y: 0.0
  acc_lim_theta: 0.6

# Goal Tolerance Parameters
  xy_goal_tolerance: 0.10
  yaw_goal_tolerance: 0.10
  goal_distance_bias: 0.2
  path_distance_bias: .9

# Differential-drive robot configuration
  holonomic_robot: false

# Forward Simulation Parameters
  sim_time: 1.7
  vx_samples: 3
  vtheta_samples: 20
  sim_granularity: 0.025

  dwa: true
  occdist_scale: 0.01
  heading_lookahead: 0.325
  oscillation_reset_dist: 0.05

  heading_scoring: false
  heading_scoring_timestep: 0.8
  simple_attractor: false