TrajectoryPlannerROS:

  transform_tolerance: 0.3

# Robot Configuration Parameters
  max_vel_x: 0.5
  min_vel_x: 0.1

  max_vel_theta:  1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.6
  min_in_place_rotational_vel: 0.4
  
  acc_lim_th: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

# Goal Tolerance Parameters
  yaw_goal_tolerance: 3.14
  xy_goal_tolerance: 0.15
  goal_distance_bias: 0.2
  path_distance_bias: .9

# Forward Simulation Parameters
  sim_time: 1.7
  vx_samples: 3
  vtheta_samples: 20

# Trajectory Scoring Parameters
  meter_scoring: true
  pdist_scale: 0.6
  gdist_scale: 0.8
  occdist_scale: 0.1
  heading_lookahead: 0.325
  dwa: true

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Differential-drive robot configuration
  holonomic_robot: false
  max_vel_y: 0.0
  min_vel_y: 0.0
  acc_lim_y: 0.0
  vy_samples: 0


  heading_scoring: false
  heading_scoring_timestep: 0.8
  simple_attractor: false