obstacle_range: 3.0
raytrace_range: 3.0



map_type: voxel
origin_z: 0.0
z_resolution: 0.2
z_voxels: 10
unknown_threshold: 9
mark_threshold: 0
transform_tolerance: 0.3


max_obstacle_height: 2.0


footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
footprint_padding: 0.01
#robot_radius: 0.105

inflation_radius: 0.55
cost_scaling_factor: 10.0
lethal_cost_threshold: 100


observation_sources: scan
scan: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true}