TrajectoryPlannerROS:
  acc_lim_x: 2.5
  acc_lim_theta: 3.2

  max_vel_x: 1.0
  min_vel_x: 0.0

  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.2

  holonomic_robot: false
  escape_vel: -0.1

  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false

  sim_time: 2.0
  sim_granularity: 0.02
  angular_sim_granularity: 0.02
  vx_samples: 6
  vtheta_samples: 20
  controller_frequency: 20

  meter_scoring: true
  occdist_scale: 0.1
  pdist_scale: 0.75
  gdist_scale: 1.0

  heading_lookhead: 0.325
  heading_scoring: false
  heading_scoring_timestep: 0.8
  dwa: true
  simple_attractor: false
  publish_cost_grid_pc: true 

  oscillation_reset_dist: 0.25
  escape_reset_dist: 0.1
  escape_reset_theta: 0.1

DWAPlannerROS:
  sacc_lim_x: 2.5
  acc_lim_y: 0
  acc_lim_th: 3.2

  max_vel_x: 2.0
  min_vel_x: 0.0
  max_vel_y: 0
  min_vel_y: 0

  max_trans_vel: 2.0
  min_trans_vel: 0.1

  max_rot_vel: 2.0
  min_rot_vel: 0.2

  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false