tebLocalPlannerROS:

  odom_topic: odom

  teb_autosize: True
  dt_ref: 0.3
  dt_hysteresis: 0.1
  global_plan_overwrite_oeirntation: True
  allow_init_with_backwards_motion: False
  max_global_plan_lookahead_dist: 3.0
  feasibility_check_no_poses: 5

  max_vel_x: 2.0
  max_vel_x_backwards: 2.2
  max_vel_y: 0.0 
  max_vel_theta: 2.0
  acc_lim_x: 2.5
  acc_lim_theta: 2.5
  min_turning_radius: 0.0

  footprint_model: 
    type: "point"

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  free_goal_vel: False

  min_obstacle_dist: 0.75
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.5
  obstacle_poses_affected: 30
  costmap_converter_plugin: ""
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5

  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activatte: True
  optimization_verbose: False
  penalty_epsilon: 0.1
  weight_max_vel_x: 2
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 1
  weight_kinematics_turning_radius: 1
  weight_optimaltime: 1
  weight_obstacle: 50
  weight_dynamic_obstacle: 10
  weight_adapt_factor: 2


  enable_homotopy_class_planning: True
  enable_multithreading: True
  simple_exploration: False
  max_number_classes: 4
  selection_cost:hysteresis: 1.0
  selectioon_obst_cost_scale: 1.0
  selection_alternative_time_cost: False

  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: False



